# Generated by Django 5.0.12 on 2025-03-05 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Proposal ID must be in the format 'XXXX-text-PXX', where X are digits and 'text' is 1 to 4 letters.", regex='^\\d{4}-[A-Za-z]{1,4}-P\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='sow',
            name='sow_id',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message="SOW ID must end with '-S' followed by exactly two digits (e.g., -S01).", regex='^.*-S\\d{2}$')]),
        ),
    ]
