# Generated by Django 5.0.12 on 2025-03-20 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposal_proposal_id_alter_sow_sow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sow',
            name='rfp',
            field=models.BooleanField(default=False, help_text='Check if this SOW is an RFP'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Proposal ID must be in the format 'YY-test-PNN' (e.g., 25-test-P01)", regex='^[0-9]{2}-[a-zA-Z]+-P[0-9]{2}$')]),
        ),
    ]
