# Generated by Django 5.0.12 on 2025-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_sow_bid_defense_required_sow_bid_defense_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposed_service_level',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sow',
            name='proposed_service_level',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default=None, max_length=10, null=True),
        ),
    ]
